export interface ToolMeta {
  slug: string;
  title: string;
  shortTitle: string;
  category: CategoryId;
  description: string;
  longDescription?: string;
  keywords: string[];
  implemented: boolean;
}

export type CategoryId =
  | 'academic'
  | 'attendance'
  | 'finance'
  | 'pdf'
  | 'image'
  | 'text'
  | 'engineering'
  | 'developer'
  | 'everyday'
  | 'study'
  | 'science'
  | 'language';

export const CATEGORIES: Record<CategoryId, { name: string; description: string }> = {
  academic: { name: 'Academic', description: 'GPA, CGPA, percentage and grading tools.' },
  attendance: { name: 'Attendance', description: 'Track and plan class attendance.' },
  finance: { name: 'Student Finance', description: 'Budgets, splitting bills, interest and loans.' },
  pdf: { name: 'PDF Tools', description: 'Merge, compress and edit PDF files — mostly in your browser.' },
  image: { name: 'Image Tools', description: 'Resize, compress and convert images for forms and applications.' },
  text: { name: 'Text Tools', description: 'Counters, cleaners and comparison tools for text.' },
  engineering: { name: 'Engineering & Math', description: 'Calculators for engineering and STEM coursework.' },
  developer: { name: 'Developer Tools', description: 'Everyday utilities for writing and debugging code.' },
  everyday: { name: 'Everyday', description: 'Dates, time, tipping and other daily-life calculators.' },
  study: { name: 'Study & Focus', description: 'Timers and planners to help you study with less friction.' },
  science: { name: 'Science & Lab', description: 'Lab calculators and scientific conversion tools.' },
  language: { name: 'Language Tools', description: 'Word count, grammar and writing assistance.' },
};

export function getToolsByCategory(category: CategoryId): ToolMeta[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getImplementedTools(): ToolMeta[] {
  return TOOLS.filter((t) => t.implemented);
}

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export const TOOLS: ToolMeta[] = [
  // ----------------------------------------------------------------------
  // Academic (Existing + New)
  // ----------------------------------------------------------------------
  {
    slug: 'cgpa-calculator',
    title: 'CGPA Calculator',
    shortTitle: 'CGPA',
    category: 'academic',
    description: 'Calculate your cumulative GPA from semester-wise SGPA and credits.',
    longDescription: `The CGPA (Cumulative Grade Point Average) is one of the most important metrics in a student's academic life. This calculator helps you compute your CGPA by entering the SGPA and credit hours for each semester. The formula used is the standard credit-weighted average: (sum of SGPA × credits) / total credits.`,
    keywords: ['cgpa', 'cumulative gpa', 'semester gpa'],
    implemented: true,
  },
  {
    slug: 'gpa-calculator',
    title: 'GPA Calculator',
    shortTitle: 'GPA',
    category: 'academic',
    description: 'Calculate a credit-weighted GPA from your course grades.',
    keywords: ['gpa', 'grade point average'],
    implemented: true,
  },
  {
    slug: 'sgpa-calculator',
    title: 'SGPA Calculator',
    shortTitle: 'SGPA',
    category: 'academic',
    description: 'Calculate your semester GPA from course-wise grades and credits.',
    keywords: ['sgpa', 'semester gpa'],
    implemented: true,
  },
  {
    slug: 'percentage-calculator',
    title: 'Percentage Calculator',
    shortTitle: 'Percentage',
    category: 'academic',
    description: 'Convert marks to percentage, find what percent a number is of another, or calculate percentage change.',
    keywords: ['percentage', 'percent calculator'],
    implemented: true,
  },
  {
    slug: 'required-marks-calculator',
    title: 'Required Marks Calculator',
    shortTitle: 'Required Marks',
    category: 'academic',
    description: 'Find the marks you need in a remaining exam to hit a target overall percentage.',
    keywords: ['required marks', 'target percentage'],
    implemented: true,
  },
  {
    slug: 'target-gpa-calculator',
    title: 'Target GPA Calculator',
    shortTitle: 'Target GPA',
    category: 'academic',
    description: 'Find the GPA you need in remaining credits to reach an overall target GPA.',
    keywords: ['target gpa', 'required gpa'],
    implemented: true,
  },
  {
    slug: 'grade-calculator',
    title: 'Weighted Grade Calculator',
    shortTitle: 'Grade Calculator',
    category: 'academic',
    description: 'Combine assignment, midterm and final weights into a final course grade.',
    keywords: ['grade calculator', 'weighted grade'],
    implemented: true,
  },
  {
    slug: 'exam-score-calculator',
    title: 'Exam Score Calculator',
    shortTitle: 'Exam Score',
    category: 'academic',
    description: 'Calculate your exam score with negative marking and total percentage.',
    keywords: ['exam score', 'negative marking'],
    implemented: true,
  },
  {
    slug: 'academic-progress-calculator',
    title: 'Academic Progress Calculator',
    shortTitle: 'Academic Progress',
    category: 'academic',
    description: 'Track your academic progress and find GPA needed in remaining credits.',
    keywords: ['academic progress', 'degree completion'],
    implemented: true,
  },

  // ============ NEW ACADEMIC TOOLS ============
  {
    slug: 'rank-percentile-calculator',
    title: 'Percentile & Rank Converter',
    shortTitle: 'Rank Calculator',
    category: 'academic',
    description: 'Convert between percentile and numeric rank for a given number of candidates.',
    longDescription: `A simple statistical converter between percentile and rank within a group. Enter your percentile and the total number of candidates to see the equivalent rank, or enter a rank to see the equivalent percentile. This is a plain math conversion — it does not use or predict any real exam's cutoffs or results.`,
    keywords: ['rank calculator', 'percentile calculator', 'percentile to rank'],
    implemented: true,
  },
  {
    slug: 'marks-average-calculator',
    title: 'Marks Average Calculator',
    shortTitle: 'Marks Average',
    category: 'academic',
    description: 'Calculate your average marks across multiple subjects or exams.',
    keywords: ['marks average', 'average calculator'],
    implemented: true,
  },
  {
    slug: 'cgpa-to-percentage-converter',
    title: 'CGPA to Percentage Converter',
    shortTitle: 'CGPA → %',
    category: 'academic',
    description: 'Convert your CGPA to percentage using standard conversion formulas.',
    longDescription: `Many universities require percentage equivalents of CGPA for job applications, higher studies, or scholarship forms. This tool converts CGPA to percentage using the standard formula: Percentage = (CGPA - 0.75) × 10 for a 10-point scale, or other common conversion methods. You can also customize the formula if your university uses a different one.`,
    keywords: ['cgpa to percentage', 'cgpa converter'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Attendance (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'attendance-calculator',
    title: 'Attendance Percentage Calculator',
    shortTitle: 'Attendance %',
    category: 'attendance',
    description: 'Calculate your current attendance percentage instantly.',
    keywords: ['attendance calculator', 'attendance percentage'],
    implemented: true,
  },
  {
    slug: 'attendance-classes-needed',
    title: 'Classes Needed for Target Attendance',
    shortTitle: 'Classes Needed',
    category: 'attendance',
    description: 'Find how many classes you need to attend in a row to hit a target attendance percentage.',
    keywords: ['classes needed', 'attendance shortage'],
    implemented: true,
  },
  {
    slug: 'attendance-classes-can-miss',
    title: 'Classes You Can Miss',
    shortTitle: 'Can I Miss?',
    category: 'attendance',
    description: 'Find how many upcoming classes you can skip and stay above your target attendance.',
    keywords: ['classes can miss', 'bunk calculator'],
    implemented: true,
  },
  {
    slug: 'subject-wise-attendance',
    title: 'Subject-wise Attendance Tracker',
    shortTitle: 'Subject Tracker',
    category: 'attendance',
    description: 'Track attendance across multiple subjects at once and see which ones are at risk.',
    keywords: ['subject wise attendance', 'attendance dashboard'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Finance (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'expense-splitter',
    title: 'Roommate Expense Splitter',
    shortTitle: 'Split Expenses',
    category: 'finance',
    description: 'Split shared rent, groceries or trip costs fairly and see who owes whom.',
    keywords: ['expense splitter', 'split bills'],
    implemented: true,
  },
  {
    slug: 'grocery-expense-splitter',
    title: 'Shared Grocery & Expense Splitter',
    shortTitle: 'Grocery Splitter',
    category: 'finance',
    description: 'Split an itemized grocery or group order fairly — different items per person, plus delivery, tax, fees and discounts.',
    keywords: ['grocery splitter', 'itemized bill split'],
    implemented: true,
  },
  {
    slug: 'simple-interest-calculator',
    title: 'Simple Interest Calculator',
    shortTitle: 'Simple Interest',
    category: 'finance',
    description: 'Calculate simple interest and total payable amount.',
    keywords: ['simple interest calculator'],
    implemented: true,
  },
  {
    slug: 'compound-interest-calculator',
    title: 'Compound Interest Calculator',
    shortTitle: 'Compound Interest',
    category: 'finance',
    description: 'Calculate compound interest with custom compounding frequency.',
    keywords: ['compound interest calculator'],
    implemented: true,
  },
  {
    slug: 'emi-calculator',
    title: 'EMI / Loan Calculator',
    shortTitle: 'EMI Calculator',
    category: 'finance',
    description: 'Calculate monthly EMI, total interest and total payment for a loan.',
    keywords: ['emi calculator', 'loan calculator'],
    implemented: true,
  },
  {
    slug: 'savings-goal-calculator',
    title: 'Savings Goal Calculator',
    shortTitle: 'Savings Goal',
    category: 'finance',
    description: 'Find out how many months it will take to reach a savings goal.',
    keywords: ['savings goal calculator'],
    implemented: true,
  },
  {
    slug: 'monthly-budget-calculator',
    title: 'Monthly Budget Calculator',
    shortTitle: 'Monthly Budget',
    category: 'finance',
    description: 'Track your income and expenses with category-based budget planning.',
    keywords: ['budget calculator', 'monthly budget'],
    implemented: true,
  },

  // ============ NEW FINANCE TOOLS ============
  {
    slug: 'tax-deduction-calculator',
    title: 'Tax Deduction Calculator',
    shortTitle: 'Tax Calculator',
    category: 'finance',
    description: 'Calculate your income tax and deductions under various tax regimes.',
    longDescription: `This tool helps you estimate your income tax liability under different tax regimes (old vs new). Enter your annual income, deductions (like 80C investments, HRA, etc.), and the tool calculates your taxable income, tax payable, and effective tax rate. This is essential for students taking internships, part-time jobs, or planning their finances.`,
    keywords: ['tax calculator', 'income tax', 'deduction calculator'],
    implemented: true,
  },
  {
    slug: 'bmi-calculator',
    title: 'BMI Calculator',
    shortTitle: 'BMI',
    category: 'finance',
    description: 'Calculate your Body Mass Index and see your healthy weight range.',
    longDescription: `Body Mass Index (BMI) is a quick way to check if your weight is in a healthy range for your height. Enter your height and weight, and the tool calculates your BMI with a classification (underweight, normal, overweight, obese). This is useful for health monitoring and gym planning.`,
    keywords: ['bmi calculator', 'body mass index'],
    implemented: true,
  },
  {
    slug: 'currency-converter',
    title: 'Currency Converter',
    shortTitle: 'Currency',
    category: 'finance',
    description: 'Convert between major currencies for travel and international payments.',
    longDescription: `Convert amounts between USD, EUR, GBP, INR, JPY, and other major currencies. This is useful for students planning international travel, studying abroad, or making online payments in foreign currency. The tool uses approximate exchange rates (you should verify the live rate before making any transaction).`,
    keywords: ['currency converter', 'exchange rate'],
    implemented: true,
  },
  {
    slug: 'car-payment-calculator',
    title: 'Car Payment Calculator',
    shortTitle: 'Car EMI',
    category: 'finance',
    description: 'Calculate monthly car loan payments and total cost of ownership.',
    longDescription: `Planning to buy a car after graduation? This tool calculates your monthly car payment based on the loan amount, interest rate, and tenure. It shows the total interest you'll pay and the total cost of the car including financing.`,
    keywords: ['car payment', 'auto loan', 'car loan calculator'],
    implemented: true,
  },
  {
    slug: 'retirement-calculator',
    title: 'Retirement Savings Calculator',
    shortTitle: 'Retirement',
    category: 'finance',
    description: 'Estimate how much you need to save for retirement.',
    longDescription: `It's never too early to think about retirement. This tool estimates how much you need to save monthly to reach your retirement goal, factoring in inflation, expected returns, and your current age. Start early — even small monthly savings grow significantly with compound interest.`,
    keywords: ['retirement calculator', 'savings plan'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // PDF (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'pdf-merge',
    title: 'Merge PDF',
    shortTitle: 'Merge PDF',
    category: 'pdf',
    description: 'Combine multiple PDF files into one — processed entirely in your browser.',
    keywords: ['merge pdf', 'combine pdf'],
    implemented: true,
  },
  {
    slug: 'pdf-split',
    title: 'Split PDF',
    shortTitle: 'Split PDF',
    category: 'pdf',
    description: 'Extract a page range from a PDF into a new file, entirely in your browser.',
    keywords: ['split pdf', 'extract pdf pages'],
    implemented: true,
  },
  {
    slug: 'compress-pdf',
    title: 'Compress PDF',
    shortTitle: 'Compress PDF',
    category: 'pdf',
    description: 'Shrink PDF file size — strong image-based compression or lossless text-preserving mode.',
    longDescription: `Two compression modes: Strong Compression re-encodes each page as an optimized image for large size reductions (typically 70-90% for image-heavy or scanned PDFs), trading away text selectability. Lossless mode keeps your text fully selectable and searchable with no quality loss, but only removes structural overhead — a mostly-text PDF is already close to its minimum size and won't shrink dramatically without that trade-off.`,
    keywords: ['compress pdf', 'reduce pdf size'],
    implemented: true,
  },
  {
    slug: 'image-to-pdf',
    title: 'JPG/PNG to PDF',
    shortTitle: 'Image → PDF',
    category: 'pdf',
    description: 'Combine images into a single PDF document, in your browser.',
    keywords: ['jpg to pdf', 'png to pdf'],
    implemented: true,
  },

  // ============ NEW PDF TOOLS ============
  {
    slug: 'pdf-to-image',
    title: 'PDF to Image Converter',
    shortTitle: 'PDF → Image',
    category: 'pdf',
    description: 'Convert PDF pages to JPG or PNG images.',
    longDescription: `Convert each page of a PDF into a high-quality JPG or PNG image. This is useful for extracting diagrams, sharing specific pages, or preparing PDF content for social media. All conversion happens in your browser using pdf.js, so your documents remain private.`,
    keywords: ['pdf to image', 'pdf to jpg', 'pdf to png'],
    implemented: true,
  },
  {
    slug: 'pdf-watermark',
    title: 'PDF Watermark & Stamp',
    shortTitle: 'PDF Watermark',
    category: 'pdf',
    description: 'Add text watermark or stamp to PDF pages.',
    longDescription: `Add a watermark (e.g., "CONFIDENTIAL", your name, or "DRAFT") to your PDF pages. You can customize the position, rotation, opacity, and font size. This is useful for protecting your work, sharing drafts, or adding school branding.`,
    keywords: ['pdf watermark', 'pdf stamp', 'add watermark to pdf'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Image (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'image-compressor',
    title: 'Image Compressor',
    shortTitle: 'Compress Image',
    category: 'image',
    description: 'Compress JPG/PNG images to a target size for form uploads, entirely in your browser.',
    keywords: ['image compressor', 'compress image'],
    implemented: true,
  },
  {
    slug: 'image-resizer',
    title: 'Image Resizer',
    shortTitle: 'Resize Image',
    category: 'image',
    description: 'Resize images to exact pixel dimensions, e.g. for passport photos.',
    keywords: ['image resizer', 'resize photo'],
    implemented: true,
  },
  {
    slug: 'image-format-converter',
    title: 'Image Format Converter',
    shortTitle: 'Convert Image',
    category: 'image',
    description: 'Convert between JPG, PNG and WebP in your browser.',
    keywords: ['jpg to png', 'png to jpg'],
    implemented: true,
  },

  // ============ NEW IMAGE TOOLS ============
  {
    slug: 'image-editor',
    title: 'Image Editor (Crop, Rotate, Flip)',
    shortTitle: 'Image Editor',
    category: 'image',
    description: 'Crop (drag to select), rotate, flip, and adjust brightness/contrast/saturation — all in one editor.',
    longDescription: `A complete image editor for quick adjustments: drag to crop exactly the area you want, rotate, flip horizontally or vertically, adjust brightness, contrast, and saturation, or convert to grayscale — then download once you're happy with the result. All editing happens client-side using the Canvas API, so your images are never uploaded.`,
    keywords: ['image editor', 'rotate image', 'flip image'],
    implemented: true,
  },
  {
    slug: 'image-color-picker',
    title: 'Image Color Picker',
    shortTitle: 'Color Picker',
    category: 'image',
    description: 'Pick colors from any image and get HEX/RGB values.',
    longDescription: `Upload any image and click on it to extract the color at that point. The tool shows the HEX, RGB, and HSL values of the picked color. This is useful for designers, students working on UI projects, or anyone who needs to match colors.`,
    keywords: ['color picker', 'extract color from image'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Text (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'word-counter',
    title: 'Word & Character Counter',
    shortTitle: 'Word Counter',
    category: 'text',
    description: 'Count words, characters, sentences, estimate reading time, and see your most repeated words.',
    longDescription: `Get a full breakdown of your text — word and character counts, sentence and paragraph counts, estimated reading and speaking time — plus a ranked list of your most frequently repeated words, so you can spot overused words in essays and reports and vary your vocabulary.`,
    keywords: ['word counter', 'character counter', 'word repetition', 'frequency counter'],
    implemented: true,
  },
  {
    slug: 'text-cleaner',
    title: 'Remove Extra Spaces & Duplicate Lines',
    shortTitle: 'Text Cleaner',
    category: 'text',
    description: 'Clean up messy pasted text: trim spaces, remove duplicate or empty lines, sort lines.',
    keywords: ['remove extra spaces', 'text cleaner'],
    implemented: true,
  },
  {
    slug: 'find-and-replace',
    title: 'Find and Replace',
    shortTitle: 'Find & Replace',
    category: 'text',
    description: 'Find and replace text, with optional regular-expression support.',
    keywords: ['find and replace'],
    implemented: true,
  },
  {
    slug: 'text-diff',
    title: 'Text Comparison (Diff)',
    shortTitle: 'Text Diff',
    category: 'text',
    description: 'Compare two blocks of text and see what changed, line by line.',
    keywords: ['text diff', 'compare text'],
    implemented: true,
  },
  {
    slug: 'case-converter',
    title: 'Case Converter',
    shortTitle: 'Case Converter',
    category: 'text',
    description: 'Convert text to uppercase, lowercase, title case, camelCase and more.',
    keywords: ['case converter'],
    implemented: true,
  },

  // ============ NEW TEXT TOOLS ============
  {
    slug: 'spell-checker',
    title: 'Spell Checker',
    shortTitle: 'Spell Check',
    category: 'language',
    description: 'Check spelling and grammar in your text.',
    longDescription: `A browser-based spell checker that identifies misspelled words and suggests corrections. This is useful for quick proofreading of assignments, emails, and essays. All checking happens locally — your text is never sent to a server.`,
    keywords: ['spell checker', 'grammar checker'],
    implemented: true,
  },
  {
    slug: 'text-to-speech',
    title: 'Text to Speech Reader',
    shortTitle: 'Text Reader',
    category: 'language',
    description: 'Listen to your text read aloud using your browser\'s speech synthesis.',
    longDescription: `Convert any text to speech and listen to it. This is useful for proofreading (you catch errors by ear), studying while commuting, or assisting with learning. Uses your browser's built-in Web Speech API — no text is sent to a server.`,
    keywords: ['text to speech', 'read aloud', 'tts'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Engineering (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'unit-converter',
    title: 'Unit Converter',
    shortTitle: 'Unit Converter',
    category: 'engineering',
    description: 'Convert length, weight, volume, area, speed and data units.',
    keywords: ['unit converter'],
    implemented: true,
  },
  {
    slug: 'number-base-converter',
    title: 'Number Base Converter',
    shortTitle: 'Base Converter',
    category: 'engineering',
    description: 'Convert between binary, decimal, octal and hexadecimal.',
    keywords: ['binary to decimal', 'number base'],
    implemented: true,
  },
  {
    slug: 'statistics-calculator',
    title: 'Mean, Median, Mode & Std Deviation',
    shortTitle: 'Statistics',
    category: 'engineering',
    description: 'Calculate mean, median, mode, variance and standard deviation for a dataset.',
    keywords: ['mean median mode', 'standard deviation'],
    implemented: true,
  },
  {
    slug: 'ohms-law-calculator',
    title: "Ohm's Law Calculator",
    shortTitle: "Ohm's Law",
    category: 'engineering',
    description: 'Calculate voltage, current, resistance or power from any two known values.',
    keywords: ["ohm's law calculator"],
    implemented: true,
  },
  {
    slug: 'scientific-calculator',
    title: 'Scientific Calculator',
    shortTitle: 'Scientific Calc',
    category: 'engineering',
    description: 'A full scientific calculator with proper order of operations, trig, logs, memory, and more.',
    longDescription: `A complete scientific calculator that evaluates full expressions with correct operator precedence and parentheses — not just one operation at a time. Includes DEG/RAD modes, trigonometric and inverse trigonometric functions, logarithms (log, ln, 10^x, e^x), powers and roots, factorial, memory (M+, M-, MR, MC), an Ans key, and the constants π and e.`,
    keywords: ['scientific calculator'],
    implemented: true,
  },
  {
    slug: 'matrix-calculator',
    title: 'Matrix Calculator',
    shortTitle: 'Matrix Calc',
    category: 'engineering',
    description: 'Add, subtract, multiply matrices, or find the transpose, determinant, and inverse.',
    longDescription: `Work with up to 8 matrices at once, each with its own size (up to 10×10). Add, subtract, or multiply any two, or run transpose, determinant, inverse, or scalar multiplication on a single matrix. Determinant and inverse use Gaussian/Gauss-Jordan elimination with partial pivoting, so results stay accurate even for larger matrices.`,
    keywords: ['matrix', 'matrix addition', 'matrix multiplication', 'matrix transpose', 'matrix inverse', 'determinant'],
    implemented: true,
  },
  {
    slug: 'permutation-combination-calculator',
    title: 'Permutation & Combination Calculator',
    shortTitle: 'Permutation',
    category: 'engineering',
    description: 'Calculate permutations and combinations for n and r values.',
    keywords: ['permutation', 'combination', 'nPr'],
    implemented: true,
  },

  // ============ NEW ENGINEERING TOOLS ============
  {
    slug: 'vector-calculator',
    title: 'Vector Calculator',
    shortTitle: 'Vector Calc',
    category: 'engineering',
    description: 'Add, subtract, and calculate dot/cross products of vectors.',
    longDescription: `A vector calculator for physics and math students. You can add, subtract, and compute the dot product and cross product of 2D and 3D vectors. It also shows the magnitude and angle of each vector.`,
    keywords: ['vector calculator', 'dot product', 'cross product'],
    implemented: true,
  },
  {
    slug: 'quadratic-equation-solver',
    title: 'Quadratic Equation Solver',
    shortTitle: 'Quadratic Solver',
    category: 'engineering',
    description: 'Solve quadratic equations and find the roots.',
    longDescription: `Solve any quadratic equation ax² + bx + c = 0 and get the real or complex roots. The tool shows each step of the calculation using the quadratic formula. Useful for algebra homework, physics problems, and engineering coursework. For higher-degree equations (cubic and above), use the Polynomial Equation Solver.`,
    keywords: ['quadratic equation', 'roots calculator'],
    implemented: true,
  },
  {
    slug: 'polynomial-equation-solver',
    title: 'Polynomial Equation Solver',
    shortTitle: 'Polynomial Solver',
    category: 'engineering',
    description: 'Find all roots of a polynomial equation of any degree from 1 to 8.',
    longDescription: `Solve polynomial equations of any degree from 1 to 8 (linear through degree-8) and get all real and complex roots, using a numerical root-finding method (Durand-Kerner). Unlike a quadratic-only solver, this handles cubics, quartics, and higher-degree equations with x raised to any power up to 8.`,
    keywords: ['polynomial equation', 'roots calculator', 'cubic equation', 'quartic equation', 'higher degree equation'],
    implemented: true,
  },
  {
    slug: 'integration-calculator',
    title: 'Basic Integration Calculator',
    shortTitle: 'Integration',
    category: 'engineering',
    description: 'Calculate definite integrals for common functions.',
    longDescription: `Compute definite integrals for common functions (polynomials, trigonometric, exponential) over a given range. This uses numerical methods (Simpson's rule) to approximate the value — good for verifying your calculus homework.`,
    keywords: ['integration', 'integral calculator', 'definite integral'],
    implemented: true,
  },
  {
    slug: 'differential-calculator',
    title: 'Differential Calculator',
    shortTitle: 'Derivative',
    category: 'engineering',
    description: 'Calculate derivatives of common functions.',
    longDescription: `Compute the derivative of functions like x^n, sin(x), cos(x), e^x, and more. The tool shows the step-by-step differentiation, making it useful for learning and verifying your calculus work.`,
    keywords: ['derivative', 'differential calculator'],
    implemented: true,
  },
  {
    slug: 'probability-distribution-calculator',
    title: 'Probability Distribution Calculator',
    shortTitle: 'Probability',
    category: 'engineering',
    description: 'Calculate probabilities for binomial, normal, and Poisson distributions.',
    longDescription: `Compute probabilities for common statistical distributions — binomial, normal (Gaussian), and Poisson. Enter the parameters and get the probability of your event. This is essential for statistics courses and data science students.`,
    keywords: ['probability calculator', 'binomial distribution'],
    implemented: true,
  },
  {
    slug: 'significant-figures-calculator',
    title: 'Significant Figures Calculator',
    shortTitle: 'Sig Figs',
    category: 'science',
    description: 'Round numbers to the correct number of significant figures.',
    longDescription: `In lab reports and scientific writing, correct significant figures are crucial. This tool rounds any number to your desired number of significant figures and explains the rules used. It also shows the scientific notation of the result.`,
    keywords: ['significant figures', 'sig figs'],
    implemented: true,
  },
  {
    slug: 'molar-mass-calculator',
    title: 'Molar Mass Calculator',
    shortTitle: 'Molar Mass',
    category: 'science',
    description: 'Calculate the molar mass of chemical compounds from their formula.',
    longDescription: `Enter a chemical formula (e.g., H2O, NaCl, C6H12O6) and get the molar mass in g/mol. The tool breaks down each element's atomic mass and shows the calculation. Essential for chemistry students and lab work.`,
    keywords: ['molar mass', 'molecular weight', 'chemistry calculator'],
    implemented: true,
  },
  {
    slug: 'limiting-reagent-calculator',
    title: 'Limiting Reagent Calculator',
    shortTitle: 'Limiting Reagent',
    category: 'science',
    description: 'Find the limiting reagent and theoretical yield in a chemical reaction.',
    longDescription: `In chemistry stoichiometry, identifying the limiting reagent is crucial. Enter the balanced chemical equation and the amounts of reactants, and the tool identifies the limiting reagent and calculates the theoretical yield.`,
    keywords: ['limiting reagent', 'theoretical yield', 'stoichiometry'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Developer (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'json-formatter',
    title: 'JSON Formatter & Validator',
    shortTitle: 'JSON Formatter',
    category: 'developer',
    description: 'Format, validate and minify JSON.',
    keywords: ['json formatter', 'json validator'],
    implemented: true,
  },
  {
    slug: 'base64-tool',
    title: 'Base64 Encoder / Decoder',
    shortTitle: 'Base64',
    category: 'developer',
    description: 'Encode or decode Base64 text.',
    keywords: ['base64 encode', 'base64 decode'],
    implemented: true,
  },
  {
    slug: 'url-encoder',
    title: 'URL Encoder / Decoder',
    shortTitle: 'URL Encode',
    category: 'developer',
    description: 'Encode or decode URL components.',
    keywords: ['url encoder', 'url decoder'],
    implemented: true,
  },
  {
    slug: 'uuid-generator',
    title: 'UUID Generator',
    shortTitle: 'UUID Generator',
    category: 'developer',
    description: 'Generate random UUID v4 identifiers.',
    keywords: ['uuid generator', 'guid generator'],
    implemented: true,
  },
  {
    slug: 'jwt-decoder',
    title: 'JWT Decoder',
    shortTitle: 'JWT Decoder',
    category: 'developer',
    description: 'Decode a JWT header and payload — entirely client-side, no signature verification.',
    keywords: ['jwt decoder', 'decode jwt'],
    implemented: true,
  },
  {
    slug: 'timestamp-converter',
    title: 'Unix Timestamp Converter',
    shortTitle: 'Timestamp',
    category: 'developer',
    description: 'Convert between Unix timestamps and human-readable dates.',
    keywords: ['unix timestamp converter'],
    implemented: true,
  },
  {
    slug: 'color-converter',
    title: 'HEX / RGB / HSL Converter',
    shortTitle: 'Color Converter',
    category: 'developer',
    description: 'Convert colors between HEX, RGB and HSL.',
    keywords: ['hex to rgb', 'color converter'],
    implemented: true,
  },
  {
    slug: 'regex-tester',
    title: 'Regex Tester',
    shortTitle: 'Regex Tester',
    category: 'developer',
    description: 'Test and debug regular expressions with real-time matching results.',
    keywords: ['regex tester', 'regular expression'],
    implemented: true,
  },
  {
    slug: 'hash-generator',
    title: 'Hash Generator',
    shortTitle: 'Hash Generator',
    category: 'developer',
    description: 'Generate SHA-256, SHA-512 and MD5 hashes for any text.',
    keywords: ['hash generator', 'sha256'],
    implemented: true,
  },

  // ============ NEW DEVELOPER TOOLS ============
  {
    slug: 'sql-formatter',
    title: 'SQL Query Formatter',
    shortTitle: 'SQL Formatter',
    category: 'developer',
    description: 'Format and beautify SQL queries.',
    longDescription: `Format messy SQL queries for better readability. This tool indents your queries, aligns keywords, and makes complex SQL easier to review. Useful for database assignments, debugging queries, and learning SQL best practices.`,
    keywords: ['sql formatter', 'format sql query'],
    implemented: true,
  },
  {
    slug: 'markdown-preview',
    title: 'Markdown Editor & Preview',
    shortTitle: 'Markdown',
    category: 'developer',
    description: 'Write and preview Markdown in real-time.',
    longDescription: `A simple Markdown editor with live preview. Great for writing README files, documentation, notes, or formatted content. The preview updates as you type, and you can copy the rendered HTML for use elsewhere.`,
    keywords: ['markdown editor', 'markdown preview'],
    implemented: true,
  },
  {
    slug: 'html-minifier',
    title: 'HTML Minifier',
    shortTitle: 'Minify HTML',
    category: 'developer',
    description: 'Minify HTML code for faster loading.',
    longDescription: `Reduce the size of your HTML files by removing unnecessary whitespace and comments. This improves page load speed. Paste your HTML and get the minified version ready for production.`,
    keywords: ['html minifier', 'minify html'],
    implemented: true,
  },
  {
    slug: 'css-minifier',
    title: 'CSS Minifier',
    shortTitle: 'Minify CSS',
    category: 'developer',
    description: 'Minify CSS code for faster loading.',
    longDescription: `Reduce CSS file size by removing comments, whitespace, and unnecessary semicolons. This speeds up your website. Paste your CSS and get the minified version.`,
    keywords: ['css minifier', 'minify css'],
    implemented: true,
  },
  {
    slug: 'diff-checker',
    title: 'Code Diff Checker',
    shortTitle: 'Code Diff',
    category: 'developer',
    description: 'Compare two code snippets and highlight differences.',
    longDescription: `Compare two pieces of code (or any text) and see exactly what changed. The tool highlights added, removed, and modified lines. This is useful for reviewing code changes, debugging, and learning from examples.`,
    keywords: ['code diff', 'compare code'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Everyday (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'age-calculator',
    title: 'Age Calculator',
    shortTitle: 'Age Calculator',
    category: 'everyday',
    description: 'Calculate exact age in years, months and days.',
    keywords: ['age calculator'],
    implemented: true,
  },
  {
    slug: 'date-difference-calculator',
    title: 'Date Difference Calculator',
    shortTitle: 'Date Difference',
    category: 'everyday',
    description: 'Find the number of days, months and years between two dates.',
    keywords: ['date difference calculator'],
    implemented: true,
  },
  {
    slug: 'business-days-calculator',
    title: 'Business Days Calculator',
    shortTitle: 'Business Days',
    category: 'everyday',
    description: 'Count working days between two dates, excluding weekends.',
    keywords: ['business days calculator'],
    implemented: true,
  },
  {
    slug: 'tip-calculator',
    title: 'Tip Calculator',
    shortTitle: 'Tip Calculator',
    category: 'everyday',
    description: 'Calculate tip amount and split the bill between people.',
    keywords: ['tip calculator'],
    implemented: true,
  },
  {
    slug: 'discount-calculator',
    title: 'Discount Calculator',
    shortTitle: 'Discount Calculator',
    category: 'everyday',
    description: 'Calculate the final price after a percentage discount.',
    keywords: ['discount calculator'],
    implemented: true,
  },
  {
    slug: 'gst-calculator',
    title: 'GST & Tax Calculator',
    shortTitle: 'GST Calculator',
    category: 'everyday',
    description: 'Calculate GST amounts for inclusive and exclusive prices.',
    keywords: ['gst calculator', 'tax calculator'],
    implemented: true,
  },
  {
    slug: 'time-zone-converter',
    title: 'Time Zone Converter',
    shortTitle: 'Time Zone',
    category: 'everyday',
    description: 'Convert time between different time zones around the world.',
    keywords: ['time zone converter'],
    implemented: true,
  },

  // ============ NEW EVERYDAY TOOLS ============
  {
    slug: 'world-clock',
    title: 'World Clock',
    shortTitle: 'World Clock',
    category: 'everyday',
    description: 'See current time in major cities around the world.',
    longDescription: `A live world clock showing the current time in major cities globally. Great for coordinating with friends/family abroad, online classes, or international collaboration. Updates in real-time.`,
    keywords: ['world clock', 'time zones'],
    implemented: true,
  },
  {
    slug: 'sleep-cycle-calculator',
    title: 'Sleep Cycle Calculator',
    shortTitle: 'Sleep Cycle',
    category: 'everyday',
    description: 'Find the best time to wake up or sleep based on 90-min cycles.',
    longDescription: `Optimize your sleep by waking up at the end of a sleep cycle (approx. 90 minutes each). Enter when you want to wake up and the tool tells you the best times to go to sleep, or enter when you're sleeping and find the best wake times. This helps you feel more refreshed.`,
    keywords: ['sleep cycle', 'sleep calculator'],
    implemented: true,
  },
  {
    slug: 'days-until-calculator',
    title: 'Days Until Calculator',
    shortTitle: 'Days Until',
    category: 'everyday',
    description: 'Count down to any date (birthday, event, deadline).',
    longDescription: `A simple countdown to any date — your birthday, an exam, a deadline, a trip, or any event. See exactly how many days, hours, and minutes remain.`,
    keywords: ['days until', 'countdown'],
    implemented: true,
  },
  {
    slug: 'water-intake-calculator',
    title: 'Water Intake Calculator',
    shortTitle: 'Water Intake',
    category: 'everyday',
    description: 'Calculate your daily water intake recommendation.',
    longDescription: `Stay hydrated! This tool calculates your recommended daily water intake based on your weight, activity level, and climate. It's a quick health check for students who are often busy and forget to drink enough water.`,
    keywords: ['water intake', 'hydration calculator'],
    implemented: true,
  },

  // ----------------------------------------------------------------------
  // Study (Existing)
  // ----------------------------------------------------------------------
  {
    slug: 'pomodoro-timer',
    title: 'Pomodoro Timer',
    shortTitle: 'Pomodoro',
    category: 'study',
    description: 'A focus timer using the Pomodoro technique — runs fully offline.',
    keywords: ['pomodoro timer', 'study timer'],
    implemented: true,
  },
  {
    slug: 'exam-countdown',
    title: 'Exam Countdown Timer',
    shortTitle: 'Exam Countdown',
    category: 'study',
    description: 'Count down the days, hours and minutes to your next exam.',
    keywords: ['exam countdown'],
    implemented: true,
  },
  {
    slug: 'study-planner',
    title: 'Study Planner',
    shortTitle: 'Study Planner',
    category: 'study',
    description: 'Plan your study schedule with priorities and track your progress.',
    keywords: ['study planner'],
    implemented: true,
  },
  {
    slug: 'study-session-tracker',
    title: 'Study Session Tracker',
    shortTitle: 'Session Tracker',
    category: 'study',
    description: 'Track your study sessions by subject and measure your total study time.',
    keywords: ['study tracker'],
    implemented: true,
  },

  // ============ NEW STUDY TOOLS ============
  {
    slug: 'flashcard-maker',
    title: 'Flashcard Maker',
    shortTitle: 'Flashcards',
    category: 'study',
    description: 'Create flashcards and test yourself for better retention.',
    longDescription: `Create your own flashcards and quiz yourself. Write a question/term on one side and the answer/definition on the other. The tool shuffles your cards and lets you flip them to test your recall. This active recall method is proven to improve long-term memory — perfect for exam prep.`,
    keywords: ['flashcard maker', 'study cards', 'active recall'],
    implemented: true,
  },
  {
    slug: 'mind-map-builder',
    title: 'Mind Map Builder',
    shortTitle: 'Mind Map',
    category: 'study',
    description: 'Create a simple mind map for brainstorming and note-taking.',
    longDescription: `A simple mind map tool for brainstorming, organizing ideas, and structuring notes. The visual layout helps you see connections between concepts, making it easier to understand complex topics and plan essays or projects.`,
    keywords: ['mind map', 'brainstorming tool'],
    implemented: true,
  },
  {
    slug: 'gpa-tracker',
    title: 'GPA Tracker',
    shortTitle: 'GPA Tracker',
    category: 'study',
    description: 'Track your GPA over time and see your progress.',
    longDescription: `Monitor your GPA across semesters. Add your GPA for each semester and the tool shows a graph of your progress over time. This helps you identify trends and set academic improvement goals.`,
    keywords: ['gpa tracker', 'gpa graph'],
    implemented: true,
  },
  {
    slug: 'syllabus-tracker',
    title: 'Syllabus Completion Tracker',
    shortTitle: 'Syllabus Tracker',
    category: 'study',
    description: 'Track how much of your syllabus you\'ve completed.',
    longDescription: `A checklist for tracking your syllabus completion before exams. Add your subjects and mark topics as done. The tool shows your overall completion percentage, helping you identify weak areas and prioritize your revision.`,
    keywords: ['syllabus tracker', 'study checklist'],
    implemented: true,
  },
  {
    slug: 'revision-scheduler',
    title: 'Revision Scheduler',
    shortTitle: 'Revision Scheduler',
    category: 'study',
    description: 'Schedule your revision sessions based on spaced repetition.',
    longDescription: `Plan your revision using spaced repetition — a proven technique for long-term memory. Enter your exam date and the tool creates a revision schedule that spaces out your study sessions for maximum retention.`,
    keywords: ['revision planner', 'spaced repetition'],
    implemented: true,
  },

  // ============ EXAM SCORE TOOLS (score-calculation utilities, not outcome predictors) ============
  {
    slug: 'upsc-prelims-calculator',
    title: 'UPSC Prelims Score Calculator',
    shortTitle: 'UPSC Prelims',
    category: 'academic',
    description: 'Calculate your UPSC Prelims score with negative marking.',
    longDescription: `The UPSC Prelims exam uses negative marking for incorrect answers. This tool helps you calculate your final score by entering correct, incorrect, and unattempted questions. It shows both your raw score and the score after negative marking is applied.`,
    keywords: ['upsc prelims', 'negative marking calculator'],
    implemented: true,
  },
];
